--output_dir
./outputs_debug/LEVEN/2-shot/0
--train_file
./dataset_processing/k_shot/fewshot_set/K2_LEVEN_0/train.pkl
--dev_file
./dataset_processing/k_shot/fewshot_set/K2_LEVEN_0/dev.pkl
--test_file
./dataset_processing/LEVEN/valid.jsonl
--label_dict_path
./dataset_processing/k_shot/label_dict_LEVEN.json
--max_steps
200
--batch_size
4
--logging_steps
10
--eval_steps
4
--use_label_semantics
--learning_rate
1e-4
--dataset_type
LEVEN
--queue_size
8192
--start_eval_steps
50
--max_seq_length
512
--fp_16
--drop_none_event
--device
cuda:1
--wandb
test
--wandbname
test
--dist_func
euclidean
--use_normalize
--use_in_batch_cl